version: '2'

services: 
  project:
    container_name: myapp
    image: crowdcomms/django-test:latest
    build: .
    volumes: 
      - .:/tmp/myapp
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - SECRET_KEY=abc123
