"""crowdcomms_code_test URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

#import the libraries needed 
from django.urls import path, include, re_path
from rest_framework import routers
from django.contrib import admin

# import views from different apps
from analytics.views import HelloWorld
from bunnies.views import RabbitHoleViewSet, BunnyViewSet

# define a router and register the viewsets
router = routers.DefaultRouter()
router.register('rabbitholes', RabbitHoleViewSet)
router.register('bunnies', BunnyViewSet)

# define the URL patterns that map to the views
urlpatterns = [
    # a simple HelloWorld view for testing purposes
    path('helloworld/', HelloWorld.as_view()),
    
    # include the URLs generated by the router
    path('', include(router.urls)),
    
    # URLs for the built-in authentication views provided by DRF
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    # URLs for the Django admin site
    re_path(r'^admin/', admin.site.urls),
]
